export const instructions = {
  title: "Online Exam Rules and Instructions",
  instructions: [
    "Welcome to the online examination portal. Before you begin, please read and adhere to the following rules and instructions:",
    "Ensure you have a stable internet connection throughout the duration of the exam.",
    "Make sure your device's camera and microphone are working properly.",
    "You must be logged in using your registered credentials to access the exam.",
    "Have a valid photo ID (e.g., driver's license, student ID) ready for verification if required.",
    "The exam has a fixed time limit, which will be clearly stated at the beginning.",
    "Make sure to manage your time wisely to attempt all questions within the allotted time.",
    "Your webcam will be activated throughout the exam to monitor your activity.",
    "Ensure your face and surroundings are clearly visible and well-lit during the exam.",
    "Avoid any distractions or unauthorized aids within the camera's view.",
    "The exam consists of multiple-choice questions (MCQs).",
    "Each question will have a set of options, of which only one is correct.",
    "Read each question carefully before selecting your answer.",
    "After selecting your answer, click on the 'Submit' or 'Next' button to proceed to the next question.",
    "Ensure your answers are submitted within the time limit.",
    "You can navigate between questions using the provided navigation buttons.",
    "Review your answers before final submission, if time permits.",
    "You are expected to complete the exam independently, without any external assistance or collaboration.",
    "Any form of cheating, including the use of unauthorized aids or communication with others, is strictly prohibited.",
    "Violations of exam rules, including cheating or misconduct, may result in disqualification and disciplinary actions.",
    "In case of technical issues or emergencies during the exam, contact the exam support team immediately for assistance.",
    "Once you have completed all the questions or the time limit has elapsed, your exam will be automatically submitted.",
    "Results will be communicated to you through the designated platform or email within the specified timeframe.",
    "By proceeding with the exam, you agree to abide by these rules and instructions. Good luck!",
  ],
};
