import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cx } from "@/lib/cx";
import { Providers } from "@/providers/Providers";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "TalentQuest | AI Driven Interviewing platform",
  description: "Generated by create next app",
  metadataBase: new URL("https://talent-quest.vercel.app"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cx(
          "min-h-screen font-sans antialiased scroll-smooth",
          fontSans.variable
        )}
      >
        <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <Suspense>{children}</Suspense>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
